export const ENV = {
  API: {
    URL: process.env.NEXT_PUBLIC_API_URL,
    BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  },
  EMAIL: {
    API_KEY: process.env.EMAIL_API_KEY,
    SERVICE_ID: process.env.EMAIL_SERVICE_ID,
    TEMPLATE_ID: process.env.EMAIL_TEMPLATE_ID,
    PRIVATE_KEY: process.env.EMAIL_PRIVATE_KEY,
    CONTACT: process.env.CONTACT_EMAIL,
  },
  FIREBASE: {
    API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  }
};